config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :links
  get 'landing/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "link_stats/:id", to:"links#stats", as:"link_stats"

  root to: 'landing#index'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :links_api, only: [:index,:create]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id           :integer          not null, primary key
#  user_id      :integer          not null
#  url          :string
#  visits_count :integer
#  code         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Link < ApplicationRecord
  belongs_to :user, counter_cache: true
  has_many :link_logs
  validates :url, format: { with: URI::regexp(%w(http https)), message: 'You provided invalid URL' }

  before_create :generate_code

  def generate_code
    self.code = SecureRandom.hex(3)
  end
end

app/models/link_log.rb
class LinkLog < ApplicationRecord
  belongs_to :link, counter_cache: true
  before_create :add_visitor

  def add_visitor
  	link.increment!(:visits_count)
  end


end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  first_name             :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :links
end

app/controllers/api/api_controller.rb
# frozen_string_literal: true
module Api
  class Api::ApiController < ActionController::Base
    before_action :authenticate
    skip_before_action :verify_authenticity_token
    include ErrorSerializer

    rescue_from ActionController::ParameterMissing do |exception|
      render json: { error: exception.message }, status: :bad_request
    end
    

    rescue_from ActiveRecord::RecordInvalid do |e|
      render serializer: ErrorSerializer,json: {error: {RecordInvalid: e.record.errors}}, status: 406
    end
  
    rescue_from ActiveRecord::RecordNotFound do
        render serializer: ErrorSerializer,json: {error: {RecordNotFound: "Record not found for id: #{params[:id]}"}}, status: 404    
    end 

    private
    def authenticate
      api_key = request.headers['X-Api-Key']
      @user = User.where(api_key: api_key).first if api_key
     
      unless @user
        head :unauthorized
        return false
      end
    end

    protected
    def self.set_pagination_headers(options = {})

        scope = @links 
        page = {}
        page[:first] = 1 if scope.total_pages > 1 && !scope.first_page?
        page[:last] = scope.total_pages  if scope.total_pages > 1 && !scope.last_page?
        page[:next] = scope.current_page + 1 unless scope.last_page?
        page[:prev] = scope.current_page - 1 unless scope.first_page?
    
        pagination_links = []
        page.each do |k, v|
          new_request_hash= request_params.merge({:page => v})
          pagination_links << "<#{url_without_params}?#{new_request_hash.to_param}>; rel=\"#{k}\""
        end
        headers["Link"] = pagination_links.join(", ")
     
    end
 
  
  end
end

app/controllers/api/v1/links_api_controller.rb
class Api::V1::LinksApiController <  Api::ApiController
    respond_to :json
    before_action :authenticate
   

    def index
        @links = @user.links.order('created_at DESC').page(params[:page] || 1).per(5)
        set_pagination_headers
        render json: LinkSerializer.new(@links), status: :ok
    end

    def create
        @link = @user.links.build(link_params)

        if @link.save
            render json: LinkSerializer.new(@link), status: :created
        else
            render json: ErrorSerializer.serialize(@link.errors), status: :bad_request
        end
    end

    private
    def link_params
        params
          .require(:link)
          .permit(:url)
    end

    def per_page
        (params[:per_page] || 5).to_i
    end

    def set_pagination_headers
        pc = @links
        headers["X-Total-Count"] = pc.total_count

        links = []
        links << page_link(1, "first") unless pc.first_page?
        links << page_link(pc.prev_page, "prev") if pc.prev_page
        links << page_link(pc.next_page, "next") if pc.next_page
        links << page_link(pc.total_pages, "last") unless pc.last_page?
        headers["Link"] = links.join(", ") if links.present?
    end

    def page_link(page, rel)
        base_uri = request.url.split("?").first
        "<#{base_uri}?#{request.query_parameters.merge(page: page).to_param}>; rel='#{rel}'"
    end 
  

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:edit, :update, :destroy]

  def index
    @links = current_user.links.order('created_at DESC').page(params[:page] || 1).per(5)
  end

  def show
    ip = request.remote_ip
		user_agent = request.user_agent
    @link = current_user.links.find_by(code: params[:id])
    @link.link_logs.create!(:ip=>ip,:user_agent=>user_agent)
    redirect_to @link.url
  end

  def new
    @link = Link.new
  end

  def edit
  end

  def create
    @link = current_user.links.build(link_params)

    if @link.save
      redirect_to links_path, notice: 'Link was successfully created.'
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def stats
    @link_logs = current_user.links.find(params[:id]).link_logs.group(:user_agent)
  end

  private

  def set_link
    @link = current_user.links.find(params[:id])
  end

  def link_params
  params
  .require(:link)
    .permit(:url)
  end
  
  def per_page
	 (params[:per_page] || 5).to_i
  end
  
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# All application helpers
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/landing/index.html.erb
<h1>Landing#index</h1>
<p>Find me in app/views/landing/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shortener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Links de <%=current_user.email%></h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Visits count</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.url %></td>
        <td><%= link.visits_count %></td>
        <td><%= link_to "http://localhost:3000/links/#{link.code}", "http://localhost:3000/links/#{link.code}" %></td>
        <td><%= link_to 'Stats', link_stats_url(link) %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @links %>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @link.user_id %>
</p>

<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>

<p>
  <strong>Visits count:</strong>
  <%= @link.visits_count %>
</p>

<p>
  <strong>Code:</strong>
  <%= @link.code %>
</p>

<p>
  <strong>Short link:</strong>
  <%= link_to "http://localhost:3000/links/#{@link.code}", "http://localhost:3000/links/#{@link.code}" %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/links/stats.html.erb
<h1>Stats de <%=current_user.links.find(params[:id]).code%></h1>

<table>
  <thead>
    <tr>
      <th>User Agent</th>
      <th>IP count</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @link_logs.each do |link_log| %>
      <tr>
        <td><%= link_log.user_agent %></td>
        <td><%= link_log.ip %></td>
        <td><%= %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/welcome/index.html.erb
<p>You're on Rails!</p>